name: MapReduce

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16.6
        
    - name: Set up without go module
      run: |
        go env -w GO111MODULE=off
        go get github.com/google/uuid
        
    - name: Lab 1
      run: |
        cd src/main
        sh test-mr.sh |& tee ~/mr.log
        cd ../..
